### PR TITLE
chore(name): Rename from IoT Hub to Stadtpuls

### PR DESCRIPTION
**Pull request by vogelino**

### CODE REVIEW

**Review by ff6347 — COMMENTED** [review]
Looks like a massive change. I'm not sure I'd I'll find the time to test if everything works correctly. I guess if the  deploy works and you can interact with the API it might be fine. Did you @julizet  change the endpoints in the TTN console?

**Comment by ff6347** [comment]
Also did you test if the tokens work? If eg the issuer changes, the tokens become invalid.

**Comment by vogelino** [comment]
You’re right @ff6347 we should definitively make sure ist works well. We will Test this internally before releasing. You don’t have to test it. PS: Good point with the Issuer

**Comment by ff6347** [comment]
This PR has to many conflicts. I moved lots of stuff around. I will close this and redo it. Sorry @vogelino

**Pull request closed without merging**
