### PR TITLE
feat(STADTPULS-519): expose users, sorted alphabetically / case-insensitively

### PR DESCRIPTION
**Pull request by dnsos**
This PR is a proposal to add a function that returns the `user_profiles`, sorted alphabetically _and_ case-insensitively. This has become necessary because the `sort()` from the Supabase SDK is only able to sort alphabetically case-sensitively (as is apparently the SQL/PostgreSQL default).

We need the users sorted according to their user name, but case-insensitively, see STADTPULS-519.

---

Note, for now this PR only proposes the PostgreSQL function itself. For other changes in the repo and the production and staging databases, I would need some help/guidance, @ff6347. 

---

Related frontend PR: https://github.com/technologiestiftung/stadtpuls-frontend/pull/193

### CODE REVIEW

**Review by ff6347 — APPROVED** [review]
Looks good to me. What we need to do is add it to staging manually, then it can be used as rpc

**Comment by dnsos** [comment]
Thanks @ff6347!

Can you please take another quick look? I have changed the PR to go against `staging` now, which required me to solve some merge conflicts.

**Review by ff6347 — APPROVED** [review]
LGTM. Feel free to merge if all checks pass and apply the function to staging

**Comment by dnsos** [comment]
Thanks! The function is applied to the staging DB now.

**Pull request merged**
